services:
  - type: web
    name: elearning-backend
    env: node
    plan: free
    rootDir: elearning-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://ediomoemmaeffiong:Ed10m0Ed10m0@elearninggbackend.44far0a.mongodb.net/?retryWrites=true&w=majority&appName=ELearningGBackend
      - key: JWT_SECRET
        value: your-production-jwt-secret-here
      - key: CORS_ORIGIN
        value: https://ai-improved-e-learning.vercel.app
    healthCheckPath: /
