services:
  - type: web
    name: elearning-backend
    env: node
    plan: free
    rootDir: elearning-backend
    buildCommand: npm ci --only=production
    startCommand: npm start
    # Removed postDeployCommand since deployment tasks now run on app start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://admin:adm1n@appbackend.encifsv.mongodb.net/elearning?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: ai-elearning-production-jwt-secret-2025-secure-key
      - key: CORS_ORIGIN
        value: https://ai-improved-e-learning.vercel.app
    healthCheckPath: /
